export const rangedWeaponList = [
   {
      name: "Balestrina",
      talent: "Armbrüste",
      ladezeit: "2 Akt.",
      tp: "1W6+4",
      rw: "5/25/40",
      munition: "Kugeln"
   }, {
      name: "Eisenwalder",
      talent: "Armbrüste",
      ladezeit: "2/10 Akt.",
      tp: "1W6+4",
      rw: "10/50/80",
      munition: "Bolzen"
   }, {
      name: "Handarmbrust",
      talent: "Armbrüste",
      ladezeit: "3 Akt.",
      tp: "1W6+3",
      rw: "5/25/40",
      munition: "Bolzen"
   }, {
      name: "leichte Armbrust",
      talent: "Armbrüste",
      ladezeit: "8 Akt.",
      tp: "1W6+6",
      rw: "10/50/80",
      munition: "Bolzen"
   }, {
      name: "schwere Armbrust",
      talent: "Armbrüste",
      ladezeit: "15 Akt.",
      tp: "2W6+6",
      rw: "20/100/160",
      munition: "Bolzen"
   }, {
      name: "Elfenbogen",
      talent: "Bögen",
      ladezeit: "1 Akt",
      tp: "1W6+5",
      rw: "50/100/200",
      munition: "Pfeile"
   }, {
      name: "Kompositbogen",
      talent: "Bögen",
      ladezeit: "2 Akt",
      tp: "1W6+7",
      rw: "20/100/160",
      munition: "Pfeile"
   }, {
      name: "Kurzbogen",
      talent: "Bögen",
      ladezeit: "1 Akt",
      tp: "1W6+4",
      rw: "10/50/80",
      munition: "Pfeile"
   }, {
      name: "Langbogen",
      talent: "Bögen",
      ladezeit: "2 Akt",
      tp: "1W6+8",
      rw: "20/100/160",
      munition: "Pfeile"
   }, {
      name: "Schneidzahn",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W6+4",
      rw: "2/10/15",
      munition: ""
   }, {
      name: "Stein",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W6",
      rw: "2/10/15",
      munition: ""
   }, {
      name: "Wurfbeil",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W6+3",
      rw: "2/10/15",
      munition: ""
   }, {
      name: "Wurfdolch",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W6+1",
      rw: "2/10/15",
      munition: ""
   }, {
      name: "Wurfkeule",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W6+2",
      rw: "2/10/15",
      munition: ""
   }, {
      name: "Wurfring",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W6+1",
      rw: "2/10/15",
      munition: ""
   }, {
      name: "Wurfscheibe",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W6+1",
      rw: "2/10/15",
      munition: ""
   }, {
      name: "Wurfstern",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W6+1",
      rw: "2/10/15",
      munition: ""
   }, {
      name: "Wurfspeer",
      talent: "Wurfwaffen",
      ladezeit: "2 Akt",
      tp: "2W6+2",
      rw: "5/25/40",
      munition: ""
   }, {
      name: "Nostrischer Langbogen",
      talent: "Bögen",
      ladezeit: "2 Akt",
      tp: "1W6+8",
      rw: "20/120/180",
      munition: "Pfeile"
   }, {
      name: "Feuerspeien",
      talent: "Feuerspeien",
      ladezeit: "1 Akt",
      tp: "1W6",
      rw: "1/2/3",
      munition: "speziell"
   }, {
      name: "Schleuder",
      talent: "Schleudern",
      ladezeit: "2 Akt",
      tp: "1W6+2",
      rw: "5/25/60",
      munition: "Steinchen"
   }, {
      name: "Balläster",
      talent: "Armbrüste",
      ladezeit: "2 Akt.",
      tp: "1W6+3",
      rw: "20/60/100",
      munition: "Kugeln"
   }, {
      name: "Blasrohr",
      talent: "Blasrohre",
      ladezeit: "2 Akt.",
      tp: "1W2",
      rw: "5/20/40",
      munition: "Blasrohrpfeile"
   }, {
      name: "Diskus",
      talent: "Diskusse",
      ladezeit: "2 Akt.",
      tp: "1W6+2",
      rw: "5/25/40",
      munition: ""
   }, {
      name: "Wurfnetz",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt.",
      tp: "spez.",
      rw: "1/3/5",
      munition: ""
   }, {
      name: "Apfel",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W3",
      rw: "2/4/8",
      munition: ""
   }, {
      name: "Steinchen",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W3",
      rw: "2/4/8",
      munition: ""
   }, {
      name: "Bierkrug",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W3+1",
      rw: "2/4/8",
      munition: ""
   }, {
      name: "Geschirr",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W3+1",
      rw: "2/4/8",
      munition: ""
   }, {
      name: "Vase",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W3+1",
      rw: "2/4/8",
      munition: ""
   }, {
      name: "Zauberkugel",
      talent: "Wurfwaffen",
      ladezeit: "1 Akt",
      tp: "1W6+1",
      rw: "3/6/9",
      munition: ""
   }
]

export const weaponList = [
  {
    name: "Basiliskenzunge",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "0,5 Stn",
    preis:  "50",
    bf: "12"
  },
  {
    name: "Dolch",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "0",
    rw: "kurz",
    gewicht: "0,5 Stn",
    preis:  "45",
    bf: "12"
  },
  {
    name: "Drachenzahn",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "0,75 Stn",
    preis:  "70",
    bf: "12"
  },
  {
    name: "Linkhand",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "0",
    rw: "kurz",
    gewicht: "0,75 Stn",
    preis:  "90",
    bf: "12"
  },
  {
    name: "Messer",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "-2",
    rw: "kurz",
    gewicht: "0,25 Stn",
    preis:  "10",
    bf: "12"
  },
  {
    name: "Schwerer Dolch",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "0,75 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Waqqif",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "0,5 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Florett",
    technik: "Fechtwaffen",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "+1",
    pa: "0",
    rw: "mittel",
    gewicht: "0,5 Stn",
    preis: "300",
    bf: "12"
  },
  {
    name: "Rapier",
    technik: "Fechtwaffen",
    leiteigenschaft: "GE",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+3",
    at: "+1",
    pa: "0",
    rw: "mittel",
    gewicht: "1 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Wolfsmesser",
    technik: "Fechtwaffen",
    leiteigenschaft: "GE",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+3",
    at: "+1",
    pa: "+1",
    rw: "mittel",
    gewicht: "0,5 Stn",
    preis: "300",
    bf: "12"
  },
  {
    name: "Brabakbengel",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+5",
    at: "-1",
    pa: "-2",
    rw: "mittel",
    gewicht: "2 Stn",
    preis: "170",
    bf: "12"
  },
  {
    name: "Keule",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+3",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis: "3",
    bf: "12"
  },
  {
    name: "Knüppel",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-2",
    rw: "mittel",
    gewicht: "0,5 Stn",
    preis: "0",
    bf: "12"
  },
  {
    name: "Lindwurmschläger",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "1 Stn",
    preis:  "90",
    bf: "12"
  },
  {
    name: "Magierstab, kurz",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "0,75 Stn",
    preis:  "40",
    bf: "12"
  },
  {
    name: "Magierstab, mittel",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Molokdeschnaja",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "1,25 Stn",
    preis:  "95",
    bf: "12"
  },
  {
    name: "Orknase",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+5",
    at: "-1",
    pa: "-2",
    rw: "mittel",
    gewicht: "1,75 Stn",
    preis: "120",
    bf: "12"
  },
  {
    name: "Rabenschnabel",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "-2",
    rw: "mittel",
    gewicht: "1,5 Stn",
    preis: "105",
    bf: "12"
  },
  {
    name: "Sonnenzepter",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+3",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "1,25 Stn",
    preis: "250",
    bf: "12"
  },
  {
    name: "Streitaxt",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "1,5 Stn",
    preis: "105",
    bf: "12"
  },
  {
    name: "Streitkolben",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "1,5 Stn",
    preis: "105",
    bf: "12"
  },
  {
    name: "Morgenstern",
    technik: "Kettenwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+5",
    at: "0",
    pa: "-",
    rw: "mittel",
    gewicht: "1,5 Stn",
    preis: "110",
    bf: "12"
  },
  {
    name: "Kriegslanze",
    technik: "Lanzen",
    leiteigenschaft:  "-",
    schwelle:  "-",
    grundschaden: "2W6",
    bonus: "+6",
    at: "-",
    pa: "-",
    rw: "-",
    gewicht: "3,75 Stn",
    preis: "100",
    bf: "12"
  },
  {
    name: "Schlagring",
    technik: "Raufen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "0",
    rw: "kurz",
    gewicht: "0,25 Stn",
    preis:  "25",
    bf: "12"
  },
  {
    name: "Waffenlos",
    technik: "Raufen",
    leiteigenschaft: "GE/KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "",
    at: "0",
    pa: "0",
    rw: "kurz",
    gewicht: "-",
    preis: "0",
    bf: "12"
  },
  {
    name: "Holzschild",
    technik: "Schilde",
    leiteigenschaft: "KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "",
    at: "-4",
    pa: "+1",
    rw: "kurz",
    gewicht: "3,5 Stn",
    preis:  "50",
    bf: "12"
  },
  {
    name: "Lederschild",
    technik: "Schilde",
    leiteigenschaft: "KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "",
    at: "-4",
    pa: "+1",
    rw: "kurz",
    gewicht: "2 Stn",
    preis:  "30",
    bf: "12"
  },
  {
    name: "Thorwalerschild",
    technik: "Schilde",
    leiteigenschaft: "KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-5",
    pa: "+2",
    rw: "kurz",
    gewicht: "4,5 Stn",
    preis:  "70",
    bf: "12"
  },
  {
    name: "Großschild",
    technik: "Schilde",
    leiteigenschaft: "KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-6",
    pa: "+3",
    rw: "kurz",
    gewicht: "6 Stn",
    preis: "100",
    bf: "12"
  },
  {
    name: "Barbarenschwert",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+5",
    at: "-1",
    pa: "-1",
    rw: "mittel",
    gewicht: "1,5 Stn",
    preis: "140",
    bf: "12"
  },
  {
    name: "Entermesser",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+3",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis: "120",
    bf: "12"
  },
  {
    name: "Flammenschwert",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+7",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "1 AsP/KR",
    preis: "0",
    bf: "12"
  },
  {
    name: "Flammenschwert (fern)",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "99",
    grundschaden: "1W6",
    bonus: "+7",
    at: "0",
    pa: "-",
    rw: "32 m | GS8",
    gewicht: "2 AsP/KR",
    preis: "0",
    bf: "12"
  },
  {
    name: "Haumesser",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+3",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis: "100",
    bf: "12"
  },
  {
    name: "Khunchomer",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "1,25 Stn",
    preis: "210",
    bf: "12"
  },
  {
    name: "Kurzschwert",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "0",
    rw: "kurz",
    gewicht: "0,75 Stn",
    preis: "140",
    bf: "12"
  },
  {
    name: "Langschwert",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "1 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Robbentöter",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "1 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Säbel",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+3",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis: "180",
    bf: "12"
  },
  {
    name: "Sklaventod",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "1,25 Stn",
    preis: "210",
    bf: "12"
  },
  {
    name: "Dreizack",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "lang",
    gewicht: "2 Stn",
    preis:  "80",
    bf: "12"
  },
  {
    name: "Dschadra",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+5",
    at: "0",
    pa: "-1",
    rw: "lang",
    gewicht: "2 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Hellebarde",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+6",
    at: "0",
    pa: "-2",
    rw: "lang",
    gewicht: "2,5 Stn",
    preis: "160",
    bf: "12"
  },
  {
    name: "Holzspeer",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "0",
    rw: "lang",
    gewicht: "1 Stn",
    preis: "1",
    bf: "12"
  },
  {
    name: "Kampfstab",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "+2",
    rw: "lang",
    gewicht: "1 Stn",
    preis:  "40",
    bf: "12"
  },
  {
    name: "Magierstab, lang",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "+2",
    rw: "lang",
    gewicht: "0,75 Stn",
    preis:  "80",
    bf: "12"
  },
  {
    name: "Speer",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "lang",
    gewicht: "2 Stn",
    preis:  "45",
    bf: "12"
  },
  {
    name: "Zweililie",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "+2",
    rw: "mittel",
    gewicht: "2 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Anderthalbhänder",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+6",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "2 Stn",
    preis: "320",
    bf: "12"
  },
  {
    name: "Doppelkhunchomer",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+3",
    at: "0",
    pa: "-2",
    rw: "mittel",
    gewicht: "2 Stn",
    preis: "320",
    bf: "12"
  },
  {
    name: "Großer Sklaventod",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+3",
    at: "0",
    pa: "-2",
    rw: "mittel",
    gewicht: "2 Stn",
    preis: "320",
    bf: "12"
  },
  {
    name: "Rondrakamm",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "2 Stn",
    preis: "340",
    bf: "12"
  },
  {
    name: "Tuzakmesser",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+6",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "1,75 Stn",
    preis: "360",
    bf: "12"
  },
  {
    name: "Zweihänder",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+4",
    at: "0",
    pa: "-3",
    rw: "mittel",
    gewicht: "2,5 Stn",
    preis: "360",
    bf: "12"
  },
  {
    name: "Barbarenstreitaxt",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "2W6",
    bonus: "+4",
    at: "0",
    pa: "-4",
    rw: "mittel",
    gewicht: "3,5 Stn",
    preis: "175",
    bf: "12"
  },
  {
    name: "Felsspalter",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "2W6",
    bonus: "+2",
    at: "0",
    pa: "-2",
    rw: "mittel",
    gewicht: "3 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Kriegshammer",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "2W6",
    bonus: "+3",
    at: "0",
    pa: "-3",
    rw: "mittel",
    gewicht: "3 Stn",
    preis: "170",
    bf: "12"
  },
  {
    name: "Zwergenschlägel",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "1W6",
    bonus: "+6",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "3 Stn",
    preis: "100",
    bf: "12"
  },
  {
    name: "Druidendolch",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-1",
    pa: "0",
    rw: "kurz",
    gewicht: "0,5 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Eberfänger",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "1 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Deichgabel",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "-2",
    rw: "mittel",
    gewicht: "0,5 Stn",
    preis:  "30",
    bf: "12"
  },
  {
    name: "Turnierlanze",
    technik: "Lanzen",
    leiteigenschaft:  "-",
    schwelle:  "-",
    grundschaden: "1W6",
    bonus: "+8",
    at: "-",
    pa: "-",
    rw: "-",
    gewicht: "3 Stn",
    preis:  "30",
    bf: "12"
  },
  {
    name: "Hirschfänger",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "1 Stn",
    preis: "100",
    bf: "12"
  },
  {
    name: "Turnierschwert",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "0,5 Stn",
    preis:  "20",
    bf: "12"
  },
  {
    name: "Kriegsflegel",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "-1",
    pa: "-1",
    rw: "lang",
    gewicht: "2 Stn",
    preis:  "50",
    bf: "12"
  },
  {
    name: "Saufeder",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+5",
    at: "0",
    pa: "-1",
    rw: "lang",
    gewicht: "1,75 Stn",
    preis: "100",
    bf: "12"
  },
  {
    name: "Sense",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+3",
    at: "-2",
    pa: "-1",
    rw: "lang",
    gewicht: "3,5 Stn",
    preis:  "40",
    bf: "12"
  },
  {
    name: "Sturmsense",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+5",
    at: "-1",
    pa: "-1",
    rw: "lang",
    gewicht: "1,75 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Holzfälleraxt",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "2W6",
    bonus: "+1",
    at: "0",
    pa: "-4",
    rw: "mittel",
    gewicht: "4 Stn",
    preis:  "80",
    bf: "12"
  },
  {
    name: "Stakaxt",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "-2",
    rw: "mittel",
    gewicht: "3 Stn",
    preis:  "40",
    bf: "12"
  },
  {
    name: "Andergaster",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+5",
    at: "0",
    pa: "-4",
    rw: "mittel",
    gewicht: "3,25 Stn",
    preis: "400",
    bf: "12"
  },
  {
    name: "Nostrianer",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+5",
    at: "0",
    pa: "-4",
    rw: "mittel",
    gewicht: "3,25 Stn",
    preis: "400",
    bf: "12"
  },
  {
    name: "Turnierzweihänder",
    technik: "Zweihandschwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+3",
    at: "0",
    pa: "-2",
    rw: "mittel",
    gewicht: "2,25 Stn",
    preis:  "40",
    bf: "12"
  },
  {
    name: "Eichhafener",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+5",
    at: "0",
    pa: "-4",
    rw: "mittel",
    gewicht: "3,5 Stn",
    preis: "440",
    bf: "12"
  },
  {
    name: "Harmlyner",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+5",
    at: "0",
    pa: "-4",
    rw: "mittel",
    gewicht: "3,5 Stn",
    preis: "440",
    bf: "12"
  },
  {
    name: "Andergaster Langschwert",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "1,25 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Nostrisches Langschwert",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Streitaxt der Streitenden Königreiche",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "1,5 Stn",
    preis: "105",
    bf: "12"
  },
  {
    name: "Streitkolben der Streitenden Königreiche",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "1,5 Stn",
    preis: "105",
    bf: "12"
  },
  {
    name: "Turnierschild der Streitenden Königreiche",
    technik: "Schilde",
    leiteigenschaft: "KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "",
    at: "-4",
    pa: "+1",
    rw: "kurz",
    gewicht: "3,5 Stn",
    preis:  "30",
    bf: "12"
  },
  {
    name: "Druidendolch aus Feuerstein",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-1",
    pa: "0",
    rw: "kurz",
    gewicht: "0,5 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Magierstab, lang (aus steineiche)",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "+2",
    rw: "lang",
    gewicht: "1 Stn",
    preis: "380",
    bf: "12"
  },
  {
    name: "Beil",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "-2",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis:  "20",
    bf: "12"
  },
  {
    name: "Handaxt",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "-2",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis:  "20",
    bf: "12"
  },
  {
    name: "Fackel",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "",
    at: "-1",
    pa: "-2",
    rw: "mittel",
    gewicht: "0,5 Stn",
    preis: "0,5",
    bf: "12"
  },
  {
    name: "Nudelholz",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-1",
    pa: "-2",
    rw: "mittel",
    gewicht: "0,5 Stn",
    preis:  "10",
    bf: "12"
  },
  {
    name: "Teigholz",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-1",
    pa: "-2",
    rw: "mittel",
    gewicht: "0,5 Stn",
    preis:  "10",
    bf: "12"
  },
  {
    name: "Schmiedehammer",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+3",
    at: "0",
    pa: "-3",
    rw: "mittel",
    gewicht: "1,25 Stn",
    preis: "100",
    bf: "12"
  },
  {
    name: "Sichel",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "-2",
    rw: "kurz",
    gewicht: "0,5 Stn",
    preis:  "10",
    bf: "12"
  },
  {
    name: "Fuhrmannspeitsche",
    technik: "Peitschen",
    leiteigenschaft: "FF",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "",
    at: "0",
    pa: "-",
    rw: "lang",
    gewicht: "3 Stn",
    preis:  "20",
    bf: "12"
  },
  {
    name: "Breitschwert",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+4",
    at: "-1",
    pa: "-1",
    rw: "mittel",
    gewicht: "1,5 Stn",
    preis: "180",
    bf: "12"
  },
  {
    name: "Parazonium",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+3",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "0,75 Stn",
    preis: "140",
    bf: "12"
  },
  {
    name: "Scimshar",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "0,75 Stn",
    preis: "140",
    bf: "12"
  },
  {
    name: "Dreschflegel",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-2",
    pa: "-1",
    rw: "lang",
    gewicht: "1,75 Stn",
    preis:  "30",
    bf: "12"
  },
  {
    name: "Hirtenstab",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "+2",
    rw: "lang",
    gewicht: "0,75 Stn",
    preis:  "10",
    bf: "12"
  },
  {
    name: "Kriegsflegel",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "-1",
    pa: "-1",
    rw: "lang",
    gewicht: "2 Stn",
    preis:  "50",
    bf: "12"
  },
  {
    name: "Pailos",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "2W6",
    bonus: "+3",
    at: "-1",
    pa: "-2",
    rw: "lang",
    gewicht: "4,5 Stn",
    preis: "300",
    bf: "12"
  },
  {
    name: "Sense",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+3",
    at: "-2",
    pa: "-1",
    rw: "lang",
    gewicht: "1,75 Stn",
    preis:  "40",
    bf: "12"
  },
  {
    name: "Sturmsense",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+5",
    at: "-1",
    pa: "-1",
    rw: "lang",
    gewicht: "1,75 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Amazonensäbel",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "2 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Faustschild",
    technik: "Schilde",
    leiteigenschaft: "KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "",
    at: "-3",
    pa: "0",
    rw: "kurz",
    gewicht: "1 Stn",
    preis:  "40",
    bf: "12"
  },
  {
    name: "Glefe",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+5",
    at: "0",
    pa: "-2",
    rw: "lang",
    gewicht: "2 Stn",
    preis:  "50",
    bf: "12"
  },
  {
    name: "Hakendolch",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-1",
    pa: "0",
    rw: "kurz",
    gewicht: "1,25 Stn",
    preis:  "80",
    bf: "12"
  },
  {
    name: "Jagdmesser",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "-2",
    rw: "kurz",
    gewicht: "0,25 Stn",
    preis:  "50",
    bf: "12"
  },
  {
    name: "Jagdspieß",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+5",
    at: "0",
    pa: "-1",
    rw: "lang",
    gewicht: "1,75 Stn",
    preis:  "80",
    bf: "12"
  },
  {
    name: "Katar",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "13",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "1,25 Stn",
    preis:  "50",
    bf: "12"
  },
  {
    name: "Mengbilar",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "-2",
    rw: "kurz",
    gewicht: "0,5 Stn",
    preis: "120",
    bf: "12"
  },
  {
    name: "Nachtwind",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "1,75 Stn",
    preis: "250",
    bf: "12"
  },
  {
    name: "Ochsenherde",
    technik: "Kettenwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+6",
    at: "-2",
    pa: "-",
    rw: "mittel",
    gewicht: "6 Stn",
    preis: "260",
    bf: "12"
  },
  {
    name: "Ogerfänger",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "1 Stn",
    preis: "100",
    bf: "12"
  },
  {
    name: "Ogerschelle",
    technik: "Kettenwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+2",
    at: "-2",
    pa: "-",
    rw: "mittel",
    gewicht: "4 Stn",
    preis: "180",
    bf: "12"
  },
  {
    name: "Orchidee",
    technik: "Raufen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "1 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Panzerarm",
    technik: "Raufen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "0",
    rw: "kurz",
    gewicht: "1 Stn",
    preis:  "70",
    bf: "12"
  },
  {
    name: "Richtschwert",
    technik: "Schwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+6",
    at: "-2",
    pa: "-3",
    rw: "mittel",
    gewicht: "5 Stn",
    preis: "600",
    bf: "12"
  },
  {
    name: "Schnitter",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+5",
    at: "-1",
    pa: "-1",
    rw: "lang",
    gewicht: "2 Stn",
    preis:  "80",
    bf: "12"
  },
  {
    name: "Stockdegen",
    technik: "Fechtwaffen",
    leiteigenschaft: "GE",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+2",
    at: "+1",
    pa: "0",
    rw: "mittel",
    gewicht: "1 Stn",
    preis: "350",
    bf: "12"
  },
  {
    name: "Warunker Hammer",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+6",
    at: "0",
    pa: "-3",
    rw: "lang",
    gewicht: "3,75 Stn",
    preis: "300",
    bf: "12"
  },
  {
    name: "Besen",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "-3",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis: "0,5",
    bf: "12"
  },
  {
    name: "Bratpfanne",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+3",
    at: "-1",
    pa: "-3",
    rw: "kurz",
    gewicht: "2 Stn",
    preis:  "12",
    bf: "12"
  },
  {
    name: "Bratpfanne, heiß",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "-2",
    pa: "-3",
    rw: "kurz",
    gewicht: "2 Stn",
    preis:  "12",
    bf: "12"
  },
  {
    name: "Bratpfanne",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-3",
    pa: "-3",
    rw: "kurz",
    gewicht: "0,5 Stn",
    preis: "3",
    bf: "12"
  },
  {
    name: "Flasche",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-1",
    pa: "-3",
    rw: "kurz",
    gewicht: "",
    preis: "",
    bf: "12"
  },
  {
    name: "Flasche, gesplittert",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "-4",
    rw: "kurz",
    gewicht: "",
    preis: "",
    bf: "12"
  },
  {
    name: "Stuhl",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+3",
    at: "-2",
    pa: "-2",
    rw: "mittel",
    gewicht: "",
    preis: "",
    bf: "12"
  },
  {
    name: "Stuhlbein",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "-3",
    rw: "mittel",
    gewicht: "",
    preis: "",
    bf: "12"
  },
  {
    name: "Tisch",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "17",
    grundschaden: "1W6",
    bonus: "+4",
    at: "-4",
    pa: "-1",
    rw: "mittel",
    gewicht: "",
    preis: "",
    bf: "12"
  },
  {
    name: "Bratspieß",
    technik: "Hiebwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-1",
    pa: "-2",
    rw: "mittel",
    gewicht: "3 Stn",
    preis:  "16",
    bf: "12"
  },
  {
    name: "Brecheisen",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "-3",
    rw: "mittel",
    gewicht: "5 Stn",
    preis:  "26",
    bf: "12"
  },
  {
    name: "Seife mit Tuch",
    technik: "Kettenwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W3",
    bonus: "",
    at: "-1",
    pa: "-",
    rw: "mittel",
    gewicht: "0,5 Stn",
    preis: "1",
    bf: "12"
  },
  {
    name: "Wurfhaken mit Kletterseil",
    technik: "Kettenwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-2",
    pa: "-",
    rw: "lang",
    gewicht: "1,5 Stn",
    preis: "7,3",
    bf: "12"
  },
  {
    name: "Brechstange",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "1W6",
    bonus: "+3",
    at: "-1",
    pa: "-3",
    rw: "mittel",
    gewicht: "6 Stn",
    preis:  "38",
    bf: "12"
  },
  {
    name: "Spaten",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "1W6",
    bonus: "+4",
    at: "-2",
    pa: "-4",
    rw: "mittel",
    gewicht: "2 Stn",
    preis: "8,5",
    bf: "12"
  },
  {
    name: "Spitzhacke",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "1W6",
    bonus: "+5",
    at: "-1",
    pa: "-5",
    rw: "mittel",
    gewicht: "2,75 Stn",
    preis:  "20",
    bf: "12"
  },
  {
    name: "Shakagra-Giftdolch",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "0",
    rw: "kurz",
    gewicht: "0,4 Stn",
    preis:  "80",
    bf: "12"
  },
  {
    name: "Shakagra-Hammer",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "1,25 Stn",
    preis: "175",
    bf: "12"
  },
  {
    name: "Shakagra-Buckler",
    technik: "Schilde",
    leiteigenschaft: "KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "",
    at: "-3",
    pa: "+1",
    rw: "kurz",
    gewicht: "3 Stn",
    preis: "250",
    bf: "12"
  },
  {
    name: "Shakagra-Langschild",
    technik: "Schilde",
    leiteigenschaft: "KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-5",
    pa: "+3",
    rw: "kurz",
    gewicht: "5 Stn",
    preis: "500",
    bf: "12"
  },
  {
    name: "Shakagra-Krummsäbel",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Shakagra-Schwert",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+5",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Shakagra-Kriegshammer",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "2W6",
    bonus: "+3",
    at: "0",
    pa: "-3",
    rw: "mittel",
    gewicht: "2 Stn",
    preis: "250",
    bf: "12"
  },
  {
    name: "Bannschwert, klein",
    technik: "Dolche",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "0",
    rw: "kurz",
    gewicht: "0,5 Stn",
    preis:  "45",
    bf: "12"
  },
  {
    name: "Bannschwert, mittel",
    technik: "Schwerter",
    leiteigenschaft: "GE/KK",
    schwelle: "15",
    grundschaden: "1W6",
    bonus: "+4",
    at: "0",
    pa: "0",
    rw: "mittel",
    gewicht: "1 Stn",
    preis: "200",
    bf: "12"
  },
  {
    name: "Bannschwert, groß",
    technik: "Zweihandschwerter",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "2W6",
    bonus: "+4",
    at: "0",
    pa: "-3",
    rw: "mittel",
    gewicht: "2,5 Stn",
    preis: "360",
    bf: "12"
  },
  {
    name: "Zauberkugel",
    technik: "Zweihandhiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "13",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-1",
    pa: "-4",
    rw: "kurz",
    gewicht: "2 Stn",
    preis:  "30",
    bf: "12"
  },
  {
    name: "Zauberstecken, kurz",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "0",
    pa: "-1",
    rw: "kurz",
    gewicht: "0,75 Stn",
    preis:  "30",
    bf: "12"
  },
  {
    name: "Zauberstecken, mittel",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+2",
    at: "0",
    pa: "-1",
    rw: "mittel",
    gewicht: "0,75 Stn",
    preis:  "45",
    bf: "12"
  },
  {
    name: "Zauberstecken, lang",
    technik: "Stangenwaffen",
    leiteigenschaft: "GE/KK",
    schwelle: "16",
    grundschaden: "1W6",
    bonus: "+2",
    at: "-1",
    pa: "+2",
    rw: "lang",
    gewicht: "0,75 Stn",
    preis:  "60",
    bf: "12"
  },
  {
    name: "Laute",
    technik: "Hiebwaffen",
    leiteigenschaft: "KK",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "+1",
    at: "-1",
    pa: "-3",
    rw: "mittel",
    gewicht: "2 Stn",
    preis: "150",
    bf: "12"
  },
  {
    name: "Flöte",
    technik: "Hiebwaffen",
    leiteigenschaft: "GE",
    schwelle: "14",
    grundschaden: "1W6",
    bonus: "",
    at: "-1",
    pa: "-4",
    rw: "kurz",
    gewicht: "0,25 Stn",
    preis: "2",
    bf: "12"
  }
];

export const armorList = [
  {
    rs: "0",
    be: "0",
    zusatz: "-",
    Gewicht: "1 Stn",
    breich: "",
    name: "normale Kleidung",
    preis: "-",
    stabilitaet: "4"
  },
  {
    rs: "0",
    be: "0",
    zusatz: "-",
    Gewicht: "1 Stn",
    breich: "",
    name: "Felle",
    preis: "-",
    stabilitaet: "4"
  },
  {
    rs: "0",
    be: "0",
    zusatz: "-",
    Gewicht: "1 Stn",
    breich: "",
    name: "nackt",
    preis: "-",
    stabilitaet: "-"
  },
  {
    rs: "1",
    be: "0",
    zusatz: "-1/-1",
    Gewicht: "2 Stn",
    breich: "",
    name: "schwere Kleidung",
    preis: "-",
    stabilitaet: "5"
  },
  {
    rs: "1",
    be: "0",
    zusatz: "-1/-1",
    Gewicht: "2 Stn",
    breich: "",
    name: "Winterkleidung",
    preis: "-",
    stabilitaet: "5"
  },
  {
    rs: "2",
    be: "1",
    zusatz: "-",
    Gewicht: "3 Stn",
    breich: "",
    name: "Stoffrüstung",
    preis: "75",
    stabilitaet: "6"
  },
  {
    rs: "2",
    be: "1",
    zusatz: "-",
    Gewicht: "3 Stn",
    breich: "",
    name: "Gambeson",
    preis: "75",
    stabilitaet: "6"
  },
  {
    rs: "3",
    be: "1",
    zusatz: "-1/-1",
    Gewicht: "6 Stn",
    breich: "",
    name: "Lederrüstung",
    preis: "150",
    stabilitaet: "8"
  },
  {
    rs: "4",
    be: "2",
    zusatz: "-",
    Gewicht: "12 Stn",
    breich: "",
    name: "Kettenrüstung",
    preis: "250",
    stabilitaet: "13"
  },
  {
    rs: "5",
    be: "2",
    zusatz: "-1/-1",
    Gewicht: "18 Stn",
    breich: "",
    name: "Schuppenrüstung",
    preis: "400",
    stabilitaet: "12"
  },
  {
    rs: "6",
    be: "3",
    zusatz: "-",
    Gewicht: "25 Stn",
    breich: "",
    name: "Plattenrüstung",
    preis: "750",
    stabilitaet: "11"
  },
  {
    rs: "8",
    be: "5",
    zusatz: "-",
    Gewicht: "40 Stn",
    breich: "",
    name: "Turnierrüstung",
    preis: "3000",
    stabilitaet: "10"
  },
  {
    rs: "4",
    be: "2",
    zusatz: "-",
    Gewicht: "10 Stn",
    breich: "",
    name: "Holzrüstung",
    preis: "300",
    stabilitaet: "9"
  },
  {
    rs: "3",
    be: "1",
    zusatz: "-1/-1",
    Gewicht: "10 Stn",
    breich: "",
    name: "Hornrüstung",
    preis: "140",
    stabilitaet: "8"
  },
  {
    rs: "2",
    be: "1",
    zusatz: "-",
    Gewicht: "6 Stn",
    breich: "",
    name: "Knochenrüstung",
    preis: "80",
    stabilitaet: "6"
  },
  {
    rs: "3",
    be: "1",
    zusatz: "-1/-1",
    Gewicht: "5 Stn",
    breich: "",
    name: "Iryanrüstung",
    preis: "250",
    stabilitaet: "8"
  },
  {
    rs: "4",
    be: "2",
    zusatz: "-",
    Gewicht: "10 Stn",
    breich: "",
    name: "Kettenhemd",
    preis: "250",
    stabilitaet: "13"
  },
  {
    rs: "3",
    be: "1",
    zusatz: "-1/-1",
    Gewicht: "5 Stn",
    breich: "",
    name: "Krötenhaut",
    preis: "200",
    stabilitaet: "8"
  },
  {
    rs: "3",
    be: "1",
    zusatz: "-1/-1",
    Gewicht: "6 Stn",
    breich: "",
    name: "Lederharnisch",
    preis: "150",
    stabilitaet: "8"
  },
  {
    rs: "6",
    be: "3",
    zusatz: "-",
    Gewicht: "15 Stn",
    breich: "",
    name: "leichte Platte",
    preis: "400",
    stabilitaet: "11"
  },
  {
    rs: "5",
    be: "2",
    zusatz: "-1/-1",
    Gewicht: "18 Stn",
    breich: "",
    name: "Schuppenpanzer",
    preis: "400",
    stabilitaet: "12"
  },
  {
    rs: "4",
    be: "2",
    zusatz: "-",
    Gewicht: "13 Stn",
    breich: "",
    name: "Spiegelpanzer",
    preis: "350",
    stabilitaet: "13"
  },
  {
    rs: "2",
    be: "1",
    zusatz: "-",
    Gewicht: "3 Stn",
    breich: "",
    name: "Tuchrüstung",
    preis: "75",
    stabilitaet: "6"
  },
  {
    rs: "5",
    be: "2",
    zusatz: "-",
    Gewicht: "18 Stn",
    breich: "",
    name: "Leichte Shakagra-Platte",
    preis: "400",
    stabilitaet: "11"
  },
  {
    rs: "6",
    be: "3",
    zusatz: "-",
    Gewicht: "25 Stn",
    breich: "",
    name: "Schwere Shakagra-Plattenrüstung",
    preis: "750",
    stabilitaet: "11"
  }
];

export const shieldList = [
  {
    Struktur: "-",
    mod: "0/+1",
    gewicht: "0,75 Stn",
    typ: "Dolche",
    name: "Linkhand",
    bf: "14"
  },
  {
    Struktur: "20",
    mod: "0/+1",
    gewicht: "3,5 Stn",
    typ: "Schilde",
    name: "Holzschild",
    bf: "10"
  },
  {
    Struktur: "20",
    mod: "0/+1",
    gewicht: "2 Stn",
    typ: "Schilde",
    name: "Lederschild",
    bf: "10"
  },
  {
    Struktur: "25",
    mod: "0/+2",
    gewicht: "4,5 Stn",
    typ: "Schilde",
    name: "Thorwalerschild",
    bf: "10"
  },
  {
    Struktur: "30",
    mod: "-1/+3",
    gewicht: "6 Stn",
    typ: "Schilde",
    name: "Großschild",
    bf: "10"
  },
  {
    Struktur: "25",
    mod: "0/+1",
    gewicht: "3,5 Stn",
    typ: "Schilde",
    name: "Turnierschild der Streitenden Königreiche",
    bf: "10"
  },
  {
    Struktur: "-",
    mod: "0/+1",
    gewicht: "0,75 Stn",
    typ: "Dolche",
    name: "Hakendolch",
    bf: "14"
  },
  {
    Struktur: "-",
    mod: "0/+1",
    gewicht: "1 Stn",
    typ: "Raufen",
    name: "Panzerarm",
    bf: "12"
  },
  {
    Struktur: "-",
    mod: "0/+1",
    gewicht: "1 Stn",
    typ: "Schilde",
    name: "Faustschild",
    bf: "10"
  },
  {
    Struktur: "-",
    mod: "0/+1",
    gewicht: "3 Stn",
    typ: "Schilde",
    name: "Shakagra-Buckler",
    bf: "10"
  },
  {
    Struktur: "-",
    mod: "0/+3",
    gewicht: "5 Stn",
    typ: "Schilde",
    name: "Shakagra-Langschild",
    bf: "10"
  }
]

